/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package atm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class deposit extends javax.swing.JFrame {

    /**
     * Creates new form deposit
     */
    String s,p,d;
    public static int getno(){
        int tid=1;
        tid=tid++;
        return tid;
    }
    public deposit(String s1,String p1,String d1) {
        initComponents();
        getConnection();
        s=s1;
        p=p1;
        d=d1;
    }

    private deposit() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

       public Connection getConnection(){
     String URL="jdbc:oracle:thin:@localhost:1521:XE";
     Connection con=null;
     String user="sample";
     String pass="sample";    
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            con=DriverManager.getConnection(URL,user,pass);
            return con;
     }
     catch(Exception se){
         System.out.println(se);
         return null;
     }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dep = new javax.swing.JTextField();
        depositbut = new javax.swing.JButton();
        backbut = new javax.swing.JButton();
        error = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enter the amount to be deposited");

        dep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                depKeyReleased(evt);
            }
        });

        depositbut.setText("Deposit");
        depositbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositbutMouseClicked(evt);
            }
        });
        depositbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositbutActionPerformed(evt);
            }
        });

        backbut.setText("BACK");
        backbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbutMouseClicked(evt);
            }
        });

        error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorActionPerformed(evt);
            }
        });
        error.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                errorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(backbut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(depositbut)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositbut)
                    .addComponent(backbut))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String username,cusid,passwd;
    private void depositbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositbutActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_depositbutActionPerformed

    private void backbutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbutMouseClicked
           Login l=new Login();
           l.setVisible(true);
           this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backbutMouseClicked

    private void depositbutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositbutMouseClicked
             String cid[]=new String[20];
                 String id[]=new String[20];
                 String pass[]=new String[20];
                 String SYSDATE="18/1/2018";
                 
       int e1=0;
        Connection con = getConnection();
        //String user="sample";
        //String pass="sample";    
        try{
            Statement st=con.createStatement();
            ResultSet m=st.executeQuery("SELECT * FROM account2 ");
            //System.out.println(m);
            int i=0;
            while(m.next())
            {  
                cid[i]=m.getString(1).toString();
                pass[i]=m.getString(3).toString();
                id[i]=m.getString(4).toString();
                i++;
            }
            
            //username=accnumtext.getText().toString();
            //passwd=pintext.getText().toString();
            String amt=dep.getText().toString();
            //int tid=7;
            System.out.println(s);
            for(int j=0;j<cid.length;j++){
                if(s.equals(cid[j])&&p.equals(pass[j])&&d.equals(id[j])){ 
                   System.out.println(s);
                   int l=st.executeUpdate("insert into transaction values("+getno()+",'deposit','"+SYSDATE+"',"+amt+",'"+d+"',"+s+")");
                  Thankdepo t=new Thankdepo();
                  t.setVisible(true);
                  this.dispose();
                   e1=1;
// TODO add your handling code here:
    }                                    
            
            }
            
            if(e1==0){
                JOptionPane.showMessageDialog(null,"Account number or PIN is incorrect");
            
        }
        }
        catch(Exception se){
         System.out.println(se);
         }       // TODO add your handling code here:
    }//GEN-LAST:event_depositbutMouseClicked

    private void errorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorActionPerformed

    private void errorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_errorKeyReleased
                 // TODO add your handling code here:
    }//GEN-LAST:event_errorKeyReleased

    private void depKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depKeyReleased
        String PATTERN="^[0-9]{1,9}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(dep.getText());
        if(!match.matches()){
            error.setText("TYPE IT IN NUMBER");
        }
        else{
            error.setText(null);
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_depKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbut;
    private javax.swing.JTextField dep;
    private javax.swing.JButton depositbut;
    private javax.swing.JTextField error;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
